/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuditIntelligenceRouteImport } from './routes/audit-intelligence'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as RemediationRouteImport } from './routes/remediation'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FindingsIndexRouteImport } from './routes/findings.index'
import { Route as FindingsIdRouteImport } from './routes/findings.$id'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIntelligenceRoute = AuditIntelligenceRouteImport.update({
  id: '/audit-intelligence',
  path: '/audit-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const RemediationRoute = RemediationRouteImport.update({
  id: '/remediation',
  path: '/remediation',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsIndexRoute = FindingsIndexRouteImport.update({
  id: '/findings/',
  path: '/findings/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsIdRoute = FindingsIdRouteImport.update({
  id: '/findings/$id',
  path: '/findings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/audit-intelligence': typeof AuditIntelligenceRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/remediation': typeof RemediationRoute
  '/settings': typeof SettingsRoute
  '/findings/$id': typeof FindingsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/findings/': typeof FindingsIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/audit-intelligence': typeof AuditIntelligenceRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/remediation': typeof RemediationRoute
  '/settings': typeof SettingsRoute
  '/findings/$id': typeof FindingsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/findings': typeof FindingsIndexRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/audit-intelligence': typeof AuditIntelligenceRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/remediation': typeof RemediationRoute
  '/settings': typeof SettingsRoute
  '/findings/$id': typeof FindingsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/findings/': typeof FindingsIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/audit-intelligence'
    | '/login'
    | '/logs'
    | '/remediation'
    | '/settings'
    | '/findings/$id'
    | '/reports/$id'
    | '/findings/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/audit-intelligence'
    | '/login'
    | '/logs'
    | '/remediation'
    | '/settings'
    | '/findings/$id'
    | '/reports/$id'
    | '/findings'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/audit-intelligence'
    | '/login'
    | '/logs'
    | '/remediation'
    | '/settings'
    | '/findings/$id'
    | '/reports/$id'
    | '/findings/'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuditIntelligenceRoute: typeof AuditIntelligenceRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  RemediationRoute: typeof RemediationRoute
  SettingsRoute: typeof SettingsRoute
  FindingsIdRoute: typeof FindingsIdRoute
  ReportsIdRoute: typeof ReportsIdRoute
  FindingsIndexRoute: typeof FindingsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-intelligence': {
      id: '/audit-intelligence'
      path: '/audit-intelligence'
      fullPath: '/audit-intelligence'
      preLoaderRoute: typeof AuditIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remediation': {
      id: '/remediation'
      path: '/remediation'
      fullPath: '/remediation'
      preLoaderRoute: typeof RemediationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/': {
      id: '/findings/'
      path: '/findings'
      fullPath: '/findings/'
      preLoaderRoute: typeof FindingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/$id': {
      id: '/findings/$id'
      path: '/findings/$id'
      fullPath: '/findings/$id'
      preLoaderRoute: typeof FindingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuditIntelligenceRoute: AuditIntelligenceRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  RemediationRoute: RemediationRoute,
  SettingsRoute: SettingsRoute,
  FindingsIdRoute: FindingsIdRoute,
  ReportsIdRoute: ReportsIdRoute,
  FindingsIndexRoute: FindingsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
